ALTER TABLE [dbo].[UserOpenIds]
    ADD CONSTRAINT [PK__UserOpen__3214EC072057CCD0] PRIMARY KEY CLUSTERED ([Id] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

