ALTER TABLE [dbo].[ConfirmEmailAddresses]
    ADD CONSTRAINT [PK_ConfirmEmailAddresses] PRIMARY KEY CLUSTERED ([ConfirmID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

