ALTER TABLE [dbo].[DiscussPostRevisions]
    ADD CONSTRAINT [PK_DiscussPostRevisions] PRIMARY KEY CLUSTERED ([PostRevisionID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

