ALTER TABLE [dbo].[DiscussBoards]
    ADD CONSTRAINT [PK_DiscussBoards] PRIMARY KEY CLUSTERED ([BoardID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

