ALTER TABLE [dbo].[DiscussThreads]
    ADD CONSTRAINT [PK_DiscussThreads] PRIMARY KEY CLUSTERED ([ThreadID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

