ALTER TABLE [dbo].[DiscussRequestedBoards]
    ADD CONSTRAINT [PK_DiscussRequestedBoards] PRIMARY KEY CLUSTERED ([RequestedBoardID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

