ALTER TABLE [dbo].[InstrumentTypes]
    ADD CONSTRAINT [PK_InstrumentTypes] PRIMARY KEY CLUSTERED ([TypeID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

