ALTER TABLE [dbo].[InstrumentStyles]
    ADD CONSTRAINT [PK_InstrumentStyles] PRIMARY KEY CLUSTERED ([StyleID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

