ALTER TABLE [dbo].[Instruments]
    ADD CONSTRAINT [PK_Instruments] PRIMARY KEY CLUSTERED ([InstrumentID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

