ALTER TABLE [dbo].[Jobs]
    ADD CONSTRAINT [PK_Jobs] PRIMARY KEY CLUSTERED ([JobID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

