ALTER TABLE [dbo].[VenueHours]
    ADD CONSTRAINT [PK_PianoVenueHours] PRIMARY KEY CLUSTERED ([VenueHoursID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

