ALTER TABLE [dbo].[FlagTypes]
    ADD CONSTRAINT [PK_PianoFlagTypes] PRIMARY KEY CLUSTERED ([FlagTypeID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

