ALTER TABLE [dbo].[Listings]
    ADD CONSTRAINT [PK_PianoListing] PRIMARY KEY CLUSTERED ([ListingID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

