ALTER TABLE [dbo].[Reviews]
    ADD CONSTRAINT [PK_PianoReviews] PRIMARY KEY CLUSTERED ([ReviewID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

