ALTER TABLE [dbo].[UserSuspensions]
    ADD CONSTRAINT [PK_PianoUserSuspensions] PRIMARY KEY CLUSTERED ([SuspensionID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

