ALTER TABLE [dbo].[ResumeTypes]
    ADD CONSTRAINT [PK_ResumeTypes] PRIMARY KEY CLUSTERED ([ResumeTypeID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

