ALTER TABLE [dbo].[ResetPasswordRecords]
    ADD CONSTRAINT [PK_ResetPasswordRecords] PRIMARY KEY CLUSTERED ([ResetID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

