ALTER TABLE [dbo].[SaleReviewRevisions]
    ADD CONSTRAINT [PK_SaleReviewRevisions] PRIMARY KEY CLUSTERED ([SaleReviewRevisionID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

