ALTER TABLE [dbo].[StoreReviewRevisions]
    ADD CONSTRAINT [PK_StoreReviewRevisions] PRIMARY KEY CLUSTERED ([StoreReviewRevisionID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

