ALTER TABLE [dbo].[StoreVenueHours]
    ADD CONSTRAINT [PK_StoreVenueHours] PRIMARY KEY CLUSTERED ([StoreVenueHoursID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

