ALTER TABLE [dbo].[WeekDays]
    ADD CONSTRAINT [PK_WeekDays] PRIMARY KEY CLUSTERED ([WeekDayID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

