// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace Legato.Controllers {
    public partial class ErrorController {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ErrorController() { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected ErrorController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result) {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

		[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
		protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result) {
			var callInfo = result.GetT4MVCResult();
			return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
		}


        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ErrorController Actions { get { return MVC.Error; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Error";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass {
            public readonly string NotFound = "NotFound";
            public readonly string Forbidden = "Forbidden";
            public readonly string Unauthorized = "Unauthorized";
            public readonly string Conflict = "Conflict";
            public readonly string InternalServerError = "InternalServerError";
            public readonly string BadRequest = "BadRequest";
            public readonly string AnyError = "AnyError";
        }


        static readonly ViewNames s_views = new ViewNames();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewNames Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewNames {
            public readonly string BadRequest = "~/Views/Error/BadRequest.aspx";
            public readonly string Conflict = "~/Views/Error/Conflict.aspx";
            public readonly string Forbidden = "~/Views/Error/Forbidden.aspx";
            public readonly string InternalServerError = "~/Views/Error/InternalServerError.aspx";
            public readonly string NotFound = "~/Views/Error/NotFound.aspx";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public class T4MVC_ErrorController: Legato.Controllers.ErrorController {
        public T4MVC_ErrorController() : base(Dummy.Instance) { }

        public override System.Web.Mvc.ActionResult NotFound() {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.NotFound);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Forbidden() {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Forbidden);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Unauthorized() {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Unauthorized);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Conflict() {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Conflict);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult InternalServerError() {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.InternalServerError);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult BadRequest() {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.BadRequest);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult AnyError() {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.AnyError);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591
