// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace T4MVC {
    public class SharedController {

        static readonly ViewNames s_views = new ViewNames();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewNames Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewNames {
            public readonly string _Layout = "~/Views/Shared/_Layout.cshtml";
            public readonly string _LogOnPartial = "~/Views/Shared/_LogOnPartial.cshtml";
            public readonly string Error = "~/Views/Shared/Error.aspx";
            public readonly string Error_cshtml = "~/Views/Shared/Error.cshtml";
            public readonly string LogOnUserControl = "~/Views/Shared/LogOnUserControl.ascx";
            public readonly string NavFull = "~/Views/Shared/NavFull.cshtml";
            public readonly string NavPartial = "~/Views/Shared/NavPartial.cshtml";
            static readonly _Awesome s_Awesome = new _Awesome();
            public _Awesome Awesome { get { return s_Awesome; } }
            public partial class _Awesome{
                public readonly string AjaxCheckBoxList = "~/Views/Shared/Awesome/AjaxCheckBoxList.ascx";
                public readonly string AjaxDropdown = "~/Views/Shared/Awesome/AjaxDropdown.ascx";
                public readonly string AjaxRadioList = "~/Views/Shared/Awesome/AjaxRadioList.ascx";
                public readonly string Autocomplete = "~/Views/Shared/Awesome/Autocomplete.ascx";
                public readonly string Confirm = "~/Views/Shared/Awesome/Confirm.ascx";
                public readonly string header = "~/Views/Shared/Awesome/header.ascx";
                public readonly string Lookup = "~/Views/Shared/Awesome/Lookup.ascx";
                public readonly string LookupList = "~/Views/Shared/Awesome/LookupList.ascx";
                public readonly string LookupPopup = "~/Views/Shared/Awesome/LookupPopup.ascx";
                public readonly string MultiLookup = "~/Views/Shared/Awesome/MultiLookup.ascx";
                public readonly string MultiLookupPopup = "~/Views/Shared/Awesome/MultiLookupPopup.ascx";
                public readonly string Popup = "~/Views/Shared/Awesome/Popup.ascx";
                public readonly string PopupForm = "~/Views/Shared/Awesome/PopupForm.ascx";
                public readonly string SearchForm = "~/Views/Shared/Awesome/SearchForm.ascx";
            }
        }
    }

}

#endregion T4MVC
#pragma warning restore 1591
