<?xml version="1.0" encoding="utf-8"?><Database Name="FindPianosToilets" Class="PianoDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=HP4200_TABLET\MSSQLSERVER2008;Initial Catalog=FindPianosToilets;Persist Security Info=True;User ID=pianotoiletapp" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="FindPianosToiletsConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.aspnet_Applications" Member="aspnet_Applications">
    <Type Name="aspnet_Application">
      <Column Name="ApplicationName" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="LoweredApplicationName" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="ApplicationId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Association Name="aspnet_Application_aspnet_Membership" Member="aspnet_Memberships" ThisKey="ApplicationId" OtherKey="ApplicationId" Type="aspnet_Membership" />
      <Association Name="aspnet_Application_aspnet_Path" Member="aspnet_Paths" ThisKey="ApplicationId" OtherKey="ApplicationId" Type="aspnet_Path" />
      <Association Name="aspnet_Application_aspnet_Role" Member="aspnet_Roles" ThisKey="ApplicationId" OtherKey="ApplicationId" Type="aspnet_Role" />
      <Association Name="aspnet_Application_aspnet_User" Member="aspnet_Users" ThisKey="ApplicationId" OtherKey="ApplicationId" Type="aspnet_User" />
    </Type>
  </Table>
  <Table Name="dbo.WeekDays" Member="WeekDays">
    <Type Name="WeekDay">
      <Column Name="WeekDayID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="WeekDayName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="WeekDay_PianoVenueHour" Member="PianoVenueHours" ThisKey="WeekDayID" OtherKey="DayOfWeek" Type="PianoVenueHour" />
      <Association Name="WeekDay_ToiletVenueHour" Member="ToiletVenueHours" ThisKey="WeekDayID" OtherKey="DayOfWeek" Type="ToiletVenueHour" />
    </Type>
  </Table>
  <Table Name="dbo.aspnet_Membership" Member="aspnet_Memberships">
    <Type Name="aspnet_Membership">
      <Column Name="ApplicationId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="UserId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="PasswordFormat" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PasswordSalt" Type="System.String" DbType="NVarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="MobilePIN" Type="System.String" DbType="NVarChar(16)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="LoweredEmail" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="PasswordQuestion" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="PasswordAnswer" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="IsApproved" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsLockedOut" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="LastLoginDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="LastPasswordChangedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="LastLockoutDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="FailedPasswordAttemptCount" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FailedPasswordAttemptWindowStart" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="FailedPasswordAnswerAttemptCount" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FailedPasswordAnswerAttemptWindowStart" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Comment" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="aspnet_Membership_ConfirmEmailAddress" Member="ConfirmEmailAddresses" ThisKey="UserId" OtherKey="UserID" Type="ConfirmEmailAddress" />
      <Association Name="aspnet_Application_aspnet_Membership" Member="aspnet_Application" ThisKey="ApplicationId" OtherKey="ApplicationId" Type="aspnet_Application" IsForeignKey="true" />
      <Association Name="aspnet_User_aspnet_Membership" Member="aspnet_User" ThisKey="UserId" OtherKey="UserId" Type="aspnet_User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.aspnet_Paths" Member="aspnet_Paths">
    <Type Name="aspnet_Path">
      <Column Name="ApplicationId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="PathId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Path" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="LoweredPath" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Association Name="aspnet_Path_aspnet_PersonalizationAllUser" Member="aspnet_PersonalizationAllUser" ThisKey="PathId" OtherKey="PathId" Type="aspnet_PersonalizationAllUser" Cardinality="One" />
      <Association Name="aspnet_Path_aspnet_PersonalizationPerUser" Member="aspnet_PersonalizationPerUsers" ThisKey="PathId" OtherKey="PathId" Type="aspnet_PersonalizationPerUser" />
      <Association Name="aspnet_Application_aspnet_Path" Member="aspnet_Application" ThisKey="ApplicationId" OtherKey="ApplicationId" Type="aspnet_Application" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.aspnet_PersonalizationAllUsers" Member="aspnet_PersonalizationAllUsers">
    <Type Name="aspnet_PersonalizationAllUser">
      <Column Name="PathId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="PageSettings" Type="System.Data.Linq.Binary" DbType="Image NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="LastUpdatedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="aspnet_Path_aspnet_PersonalizationAllUser" Member="aspnet_Path" ThisKey="PathId" OtherKey="PathId" Type="aspnet_Path" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.aspnet_PersonalizationPerUser" Member="aspnet_PersonalizationPerUsers">
    <Type Name="aspnet_PersonalizationPerUser">
      <Column Name="Id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="PathId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="UserId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="PageSettings" Type="System.Data.Linq.Binary" DbType="Image NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="LastUpdatedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="aspnet_Path_aspnet_PersonalizationPerUser" Member="aspnet_Path" ThisKey="PathId" OtherKey="PathId" Type="aspnet_Path" IsForeignKey="true" />
      <Association Name="aspnet_User_aspnet_PersonalizationPerUser" Member="aspnet_User" ThisKey="UserId" OtherKey="UserId" Type="aspnet_User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.aspnet_Profile" Member="aspnet_Profiles">
    <Type Name="aspnet_Profile">
      <Column Name="UserId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="PropertyNames" Type="System.String" DbType="NText NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="PropertyValuesString" Type="System.String" DbType="NText NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="PropertyValuesBinary" Type="System.Data.Linq.Binary" DbType="Image NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="LastUpdatedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="aspnet_User_aspnet_Profile" Member="aspnet_User" ThisKey="UserId" OtherKey="UserId" Type="aspnet_User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.aspnet_Roles" Member="aspnet_Roles">
    <Type Name="aspnet_Role">
      <Column Name="ApplicationId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="RoleId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="RoleName" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="LoweredRoleName" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Association Name="aspnet_Role_aspnet_UsersInRole" Member="aspnet_UsersInRoles" ThisKey="RoleId" OtherKey="RoleId" Type="aspnet_UsersInRole" />
      <Association Name="aspnet_Application_aspnet_Role" Member="aspnet_Application" ThisKey="ApplicationId" OtherKey="ApplicationId" Type="aspnet_Application" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.aspnet_SchemaVersions" Member="aspnet_SchemaVersions">
    <Type Name="aspnet_SchemaVersion">
      <Column Name="Feature" Type="System.String" DbType="NVarChar(128) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CompatibleSchemaVersion" Type="System.String" DbType="NVarChar(128) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="IsCurrentVersion" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.aspnet_Users" Member="aspnet_Users">
    <Type Name="aspnet_User">
      <Column Name="ApplicationId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="UserId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="LoweredUserName" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="MobileAlias" Type="System.String" DbType="NVarChar(16)" CanBeNull="true" />
      <Column Name="IsAnonymous" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="LastActivityDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="aspnet_User_aspnet_Membership" Member="aspnet_Membership" ThisKey="UserId" OtherKey="UserId" Type="aspnet_Membership" Cardinality="One" />
      <Association Name="aspnet_User_aspnet_PersonalizationPerUser" Member="aspnet_PersonalizationPerUsers" ThisKey="UserId" OtherKey="UserId" Type="aspnet_PersonalizationPerUser" />
      <Association Name="aspnet_User_aspnet_Profile" Member="aspnet_Profile" ThisKey="UserId" OtherKey="UserId" Type="aspnet_Profile" Cardinality="One" />
      <Association Name="aspnet_User_aspnet_UsersInRole" Member="aspnet_UsersInRoles" ThisKey="UserId" OtherKey="UserId" Type="aspnet_UsersInRole" />
      <Association Name="aspnet_User_PianoListingComment" Member="PianoListingComments" ThisKey="UserId" OtherKey="AuthorUserID" Type="PianoListingComment" />
      <Association Name="aspnet_User_PianoListingFlag" Member="PianoListingFlags" ThisKey="UserId" OtherKey="UserID" Type="PianoListingFlag" />
      <Association Name="aspnet_User_PianoListing" Member="PianoListings" ThisKey="UserId" OtherKey="OriginalSubmitterUserID" Type="PianoListing" />
      <Association Name="aspnet_User_PianoReviewComment" Member="PianoReviewComments" ThisKey="UserId" OtherKey="AuthorUserID" Type="PianoReviewComment" />
      <Association Name="aspnet_User_PianoReviewFlag" Member="PianoReviewFlags" ThisKey="UserId" OtherKey="UserID" Type="PianoReviewFlag" />
      <Association Name="aspnet_User_PianoReviewRevision" Member="PianoReviewRevisions" ThisKey="UserId" OtherKey="SubmitterUserID" Type="PianoReviewRevision" />
      <Association Name="aspnet_User_PianoUserSuspension" Member="PianoUserSuspensions" ThisKey="UserId" OtherKey="UserID" Type="PianoUserSuspension" />
      <Association Name="aspnet_Application_aspnet_User" Member="aspnet_Application" ThisKey="ApplicationId" OtherKey="ApplicationId" Type="aspnet_Application" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.aspnet_UsersInRoles" Member="aspnet_UsersInRoles">
    <Type Name="aspnet_UsersInRole">
      <Column Name="UserId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="RoleId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="aspnet_Role_aspnet_UsersInRole" Member="aspnet_Role" ThisKey="RoleId" OtherKey="RoleId" Type="aspnet_Role" IsForeignKey="true" />
      <Association Name="aspnet_User_aspnet_UsersInRole" Member="aspnet_User" ThisKey="UserId" OtherKey="UserId" Type="aspnet_User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.aspnet_WebEvent_Events" Member="aspnet_WebEvent_Events">
    <Type Name="aspnet_WebEvent_Event">
      <Column Name="EventId" Type="System.String" DbType="Char(32) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="EventTimeUtc" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="EventTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="EventType" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="EventSequence" Type="System.Decimal" DbType="Decimal(19,0) NOT NULL" CanBeNull="false" />
      <Column Name="EventOccurrence" Type="System.Decimal" DbType="Decimal(19,0) NOT NULL" CanBeNull="false" />
      <Column Name="EventCode" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="EventDetailCode" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Message" Type="System.String" DbType="NVarChar(1024)" CanBeNull="true" />
      <Column Name="ApplicationPath" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="ApplicationVirtualPath" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="MachineName" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="RequestUrl" Type="System.String" DbType="NVarChar(1024)" CanBeNull="true" />
      <Column Name="ExceptionType" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="Details" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
    </Type>
  </Table>
  <Table Name="dbo.ConfirmEmailAddresses" Member="ConfirmEmailAddresses">
    <Type Name="ConfirmEmailAddress">
      <Column Name="ConfirmID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="UserID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Association Name="aspnet_Membership_ConfirmEmailAddress" Member="aspnet_Membership" ThisKey="UserID" OtherKey="UserId" Type="aspnet_Membership" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PianoFlagTypes" Member="PianoFlagTypes">
    <Type Name="PianoFlagType">
      <Column Name="FlagTypeID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Association Name="PianoFlagType_PianoListingFlag" Member="PianoListingFlags" ThisKey="FlagTypeID" OtherKey="TypeID" Type="PianoListingFlag" />
      <Association Name="PianoFlagType_PianoReviewFlag" Member="PianoReviewFlags" ThisKey="FlagTypeID" OtherKey="TypeID" Type="PianoReviewFlag" />
    </Type>
  </Table>
  <Table Name="dbo.PianoListingComments" Member="PianoListingComments">
    <Type Name="PianoListingComment">
      <Column Name="CommentID" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PianoListingID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="AuthorUserID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="MessageText" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="DateOfSubmission" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="aspnet_User_PianoListingComment" Member="aspnet_User" ThisKey="AuthorUserID" OtherKey="UserId" Type="aspnet_User" IsForeignKey="true" />
      <Association Name="PianoListing_PianoListingComment" Member="PianoListing" ThisKey="PianoListingID" OtherKey="PianoID" Type="PianoListing" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PianoListingFlags" Member="PianoListingFlags">
    <Type Name="PianoListingFlag">
      <Column Name="FlagID" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ListingID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="TypeID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UserID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="FlagDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="aspnet_User_PianoListingFlag" Member="aspnet_User" ThisKey="UserID" OtherKey="UserId" Type="aspnet_User" IsForeignKey="true" />
      <Association Name="PianoFlagType_PianoListingFlag" Member="PianoFlagType" ThisKey="TypeID" OtherKey="FlagTypeID" Type="PianoFlagType" IsForeignKey="true" />
      <Association Name="PianoListing_PianoListingFlag" Member="PianoListing" ThisKey="ListingID" OtherKey="PianoID" Type="PianoListing" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PianoListings" Member="PianoListings">
    <Type Name="PianoListing">
      <Column Name="PianoID" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Lat" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="Long" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="StreetAddress" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="OriginalSubmitterUserID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="DateOfSubmission" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="PianoListing_PianoListingComment" Member="PianoListingComments" ThisKey="PianoID" OtherKey="PianoListingID" Type="PianoListingComment" />
      <Association Name="PianoListing_PianoListingFlag" Member="PianoListingFlags" ThisKey="PianoID" OtherKey="ListingID" Type="PianoListingFlag" />
      <Association Name="PianoListing_PianoReview" Member="PianoReviews" ThisKey="PianoID" OtherKey="PianoListingID" Type="PianoReview" />
      <Association Name="aspnet_User_PianoListing" Member="aspnet_User" ThisKey="OriginalSubmitterUserID" OtherKey="UserId" Type="aspnet_User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PianoReviewComments" Member="PianoReviewComments">
    <Type Name="PianoReviewComment">
      <Column Name="CommentID" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PianoReviewID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="AuthorUserID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="MessageText" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="DateOfSubmission" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="aspnet_User_PianoReviewComment" Member="aspnet_User" ThisKey="AuthorUserID" OtherKey="UserId" Type="aspnet_User" IsForeignKey="true" />
      <Association Name="PianoReview_PianoReviewComment" Member="PianoReview" ThisKey="PianoReviewID" OtherKey="PianoReviewID" Type="PianoReview" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PianoReviewFlags" Member="PianoReviewFlags">
    <Type Name="PianoReviewFlag">
      <Column Name="FlagID" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ReviewID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="TypeID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UserID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="FlagDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="aspnet_User_PianoReviewFlag" Member="aspnet_User" ThisKey="UserID" OtherKey="UserId" Type="aspnet_User" IsForeignKey="true" />
      <Association Name="PianoFlagType_PianoReviewFlag" Member="PianoFlagType" ThisKey="TypeID" OtherKey="FlagTypeID" Type="PianoFlagType" IsForeignKey="true" />
      <Association Name="PianoReview_PianoReviewFlag" Member="PianoReview" ThisKey="ReviewID" OtherKey="PianoReviewID" Type="PianoReview" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PianoReviewRevisions" Member="PianoReviewRevisions">
    <Type Name="PianoReviewRevision">
      <Column Name="PianoReviewRevisionID" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PianoReviewID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="PianoStyleID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Brand" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Model" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="RatingOverall" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RatingTuning" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="RatingToneQuality" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="RatingPlayingCapability" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Message" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="PricePerHourInUSD" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="VenueName" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="SubmitterUserID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="DateOfRevision" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="DateOfLastUsageOfPianoBySubmitter" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="RevisionNumberOfReview" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="PianoReviewRevision_PianoVenueHour" Member="PianoVenueHours" ThisKey="PianoReviewRevisionID" OtherKey="ReviewRevisionID" Type="PianoVenueHour" />
      <Association Name="aspnet_User_PianoReviewRevision" Member="aspnet_User" ThisKey="SubmitterUserID" OtherKey="UserId" Type="aspnet_User" IsForeignKey="true" />
      <Association Name="PianoReview_PianoReviewRevision" Member="PianoReview" ThisKey="PianoReviewID" OtherKey="PianoReviewID" Type="PianoReview" IsForeignKey="true" />
      <Association Name="PianoStyle_PianoReviewRevision" Member="PianoStyle" ThisKey="PianoStyleID" OtherKey="PianoStyleID" Type="PianoStyle" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PianoReviews" Member="PianoReviews">
    <Type Name="PianoReview">
      <Column Name="PianoReviewID" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PianoListingID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Association Name="PianoReview_PianoReviewComment" Member="PianoReviewComments" ThisKey="PianoReviewID" OtherKey="PianoReviewID" Type="PianoReviewComment" />
      <Association Name="PianoReview_PianoReviewFlag" Member="PianoReviewFlags" ThisKey="PianoReviewID" OtherKey="ReviewID" Type="PianoReviewFlag" />
      <Association Name="PianoReview_PianoReviewRevision" Member="PianoReviewRevisions" ThisKey="PianoReviewID" OtherKey="PianoReviewID" Type="PianoReviewRevision" />
      <Association Name="PianoListing_PianoReview" Member="PianoListing" ThisKey="PianoListingID" OtherKey="PianoID" Type="PianoListing" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PianoStyles" Member="PianoStyles">
    <Type Name="PianoStyle">
      <Column Name="PianoStyleID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="PianoStyle_PianoReviewRevision" Member="PianoReviewRevisions" ThisKey="PianoStyleID" OtherKey="PianoStyleID" Type="PianoReviewRevision" />
    </Type>
  </Table>
  <Table Name="dbo.PianoUserSuspensions" Member="PianoUserSuspensions">
    <Type Name="PianoUserSuspension">
      <Column Name="SuspensionID" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="Reason" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="SuspensionDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="ReinstateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="aspnet_User_PianoUserSuspension" Member="aspnet_User" ThisKey="UserID" OtherKey="UserId" Type="aspnet_User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PianoVenueHours" Member="PianoVenueHours">
    <Type Name="PianoVenueHour">
      <Column Name="VenueHoursID" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ReviewRevisionID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="DayOfWeek" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="StartTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="EndTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="PianoReviewRevision_PianoVenueHour" Member="PianoReviewRevision" ThisKey="ReviewRevisionID" OtherKey="PianoReviewRevisionID" Type="PianoReviewRevision" IsForeignKey="true" />
      <Association Name="WeekDay_PianoVenueHour" Member="WeekDay" ThisKey="DayOfWeek" OtherKey="WeekDayID" Type="WeekDay" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ToiletListings" Member="ToiletListings">
    <Type Name="ToiletListing">
      <Column Name="ToiletID" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Lat" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="Long" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="StreetAddress" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="OriginalSubmitterUserID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="DateOfSubmission" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="ToiletListing_ToiletReview" Member="ToiletReviews" ThisKey="ToiletID" OtherKey="ToiletListingID" Type="ToiletReview" />
    </Type>
  </Table>
  <Table Name="dbo.ToiletReviews" Member="ToiletReviews">
    <Type Name="ToiletReview">
      <Column Name="ToiletReviewID" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ToiletListingID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="ToiletStyleID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UrinalCount" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="StallCount" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SinkCount" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BabyChangingStationCount" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="RatingOverall" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RatingCleanliness" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="RatingAvailability" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TypicalWait" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Message" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="VenueID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="DateOfSubmission" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="SubmitterUserID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="DateOfLastUsageOfToiletBySubmitter" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="ToiletListing_ToiletReview" Member="ToiletListing" ThisKey="ToiletListingID" OtherKey="ToiletID" Type="ToiletListing" IsForeignKey="true" />
      <Association Name="ToiletStyle_ToiletReview" Member="ToiletStyle" ThisKey="ToiletStyleID" OtherKey="ToiletStyleID" Type="ToiletStyle" IsForeignKey="true" />
      <Association Name="ToiletVenue_ToiletReview" Member="ToiletVenue" ThisKey="VenueID" OtherKey="VenueID" Type="ToiletVenue" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ToiletStyles" Member="ToiletStyles">
    <Type Name="ToiletStyle">
      <Column Name="ToiletStyleID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="ToiletStyle_ToiletReview" Member="ToiletReviews" ThisKey="ToiletStyleID" OtherKey="ToiletStyleID" Type="ToiletReview" />
    </Type>
  </Table>
  <Table Name="dbo.ToiletVenueHours" Member="ToiletVenueHours">
    <Type Name="ToiletVenueHour">
      <Column Name="VenueHoursID" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="VenueID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="DayOfWeek" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="StartTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="EndTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="WeekDay_ToiletVenueHour" Member="WeekDay" ThisKey="DayOfWeek" OtherKey="WeekDayID" Type="WeekDay" IsForeignKey="true" />
      <Association Name="ToiletVenue_ToiletVenueHour" Member="ToiletVenue" ThisKey="VenueID" OtherKey="VenueID" Type="ToiletVenue" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ToiletVenues" Member="ToiletVenues">
    <Type Name="ToiletVenue">
      <Column Name="VenueID" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="VenueName" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Association Name="ToiletVenue_ToiletReview" Member="ToiletReviews" ThisKey="VenueID" OtherKey="VenueID" Type="ToiletReview" />
      <Association Name="ToiletVenue_ToiletVenueHour" Member="ToiletVenueHours" ThisKey="VenueID" OtherKey="VenueID" Type="ToiletVenueHour" />
    </Type>
  </Table>
</Database>