// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace Legato.Controllers {
    public partial class LegalController {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public LegalController() { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected LegalController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result) {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

		[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
		protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result) {
			var callInfo = result.GetT4MVCResult();
			return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
		}


        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public LegalController Actions { get { return MVC.Legal; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Legal";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass {
            public readonly string Index = "Index";
            public readonly string TermsOfService = "TermsOfService";
            public readonly string Privacy = "Privacy";
            public readonly string Content = "Content";
        }


        static readonly ViewNames s_views = new ViewNames();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewNames Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewNames {
            public readonly string Content = "~/Views/Legal/Content.cshtml";
            public readonly string Index = "~/Views/Legal/Index.cshtml";
            public readonly string Privacy = "~/Views/Legal/Privacy.cshtml";
            public readonly string TermsOfService = "~/Views/Legal/TermsOfService.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public class T4MVC_LegalController: Legato.Controllers.LegalController {
        public T4MVC_LegalController() : base(Dummy.Instance) { }

        public override System.Web.Mvc.ActionResult Index() {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Index);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult TermsOfService() {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.TermsOfService);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Privacy() {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Privacy);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Content() {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Content);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591
