// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace Legato.Controllers {
    public partial class SearchController {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public SearchController() { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected SearchController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result) {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

		[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
		protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result) {
			var callInfo = result.GetT4MVCResult();
			return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
		}

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult IndexPost() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.IndexPost);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult Search() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.Search);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult TagSearch() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.TagSearch);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public SearchController Actions { get { return MVC.Search; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Search";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass {
            public readonly string Index = "Index";
            public readonly string IndexPost = "IndexPost";
            public readonly string Search = "Search";
            public readonly string TagSearch = "TagSearch";
            public readonly string RegenerateIndex = "RegenerateIndex";
            public readonly string OptimizeIndex = "OptimizeIndex";
            public readonly string SpatialRegenerateIndex = "SpatialRegenerateIndex";
            public readonly string SpatialOptimizeIndex = "SpatialOptimizeIndex";
        }


        static readonly ViewNames s_views = new ViewNames();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewNames Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewNames {
            public readonly string Deactivated = "~/Views/Search/Deactivated.cshtml";
            public readonly string Index = "~/Views/Search/Index.cshtml";
            public readonly string OptimizeIndex = "~/Views/Search/OptimizeIndex.cshtml";
            public readonly string RegenerateIndex = "~/Views/Search/RegenerateIndex.cshtml";
            public readonly string Search = "~/Views/Search/Search.cshtml";
            public readonly string SpatialOptimizeIndex = "~/Views/Search/SpatialOptimizeIndex.cshtml";
            public readonly string SpatialRegenerateIndex = "~/Views/Search/SpatialRegenerateIndex.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public class T4MVC_SearchController: Legato.Controllers.SearchController {
        public T4MVC_SearchController() : base(Dummy.Instance) { }

        public override System.Web.Mvc.ActionResult Index() {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Index);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult IndexPost(string query, string tags) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.IndexPost);
            callInfo.RouteValueDictionary.Add("query", query);
            callInfo.RouteValueDictionary.Add("tags", tags);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Search(string query) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Search);
            callInfo.RouteValueDictionary.Add("query", query);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult TagSearch(string query, string tags) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.TagSearch);
            callInfo.RouteValueDictionary.Add("query", query);
            callInfo.RouteValueDictionary.Add("tags", tags);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult RegenerateIndex() {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.RegenerateIndex);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult RegenerateIndex(bool captchaValid) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.RegenerateIndex);
            callInfo.RouteValueDictionary.Add("captchaValid", captchaValid);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult OptimizeIndex() {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.OptimizeIndex);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult OptimizeIndex(bool captchaValid) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.OptimizeIndex);
            callInfo.RouteValueDictionary.Add("captchaValid", captchaValid);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult SpatialRegenerateIndex() {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.SpatialRegenerateIndex);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult SpatialRegenerateIndex(bool captchaValid) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.SpatialRegenerateIndex);
            callInfo.RouteValueDictionary.Add("captchaValid", captchaValid);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult SpatialOptimizeIndex() {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.SpatialOptimizeIndex);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult SpatialOptimizeIndex(bool captchaValid) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.SpatialOptimizeIndex);
            callInfo.RouteValueDictionary.Add("captchaValid", captchaValid);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591
